# Generated by Django 4.2.4 on 2023-08-28 16:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('phone', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(limit_value=8)])),
                ('status', models.BooleanField(default=True)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RapienviosBackend.user_type')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_date', models.DateField()),
                ('delicery_date', models.DateField()),
                ('updated_date', models.DateField()),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weigth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RapienviosBackend.shipping_status')),
                ('shipping_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RapienviosBackend.shipping_type')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RapienviosBackend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initial_date', models.DateField()),
                ('final_date', models.DateField()),
                ('shipping_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RapienviosBackend.shipping_status')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_num', models.CharField(max_length=100)),
                ('reception_date', models.DateField()),
                ('packaged_date', models.DateField()),
                ('shipping_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RapienviosBackend.shipping')),
            ],
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RapienviosBackend.package')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RapienviosBackend.user')),
            ],
        ),
    ]
