# Generated by Django 4.2.4 on 2023-09-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RapienviosBackend', '0003_alter_pricing_final_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locker',
            old_name='package_id',
            new_name='package',
        ),
        migrations.RenameField(
            model_name='locker',
            old_name='user_id',
            new_name='user',
        ),
    ]
